#!/bin/bash

set -e
set -x

function sigterm_handler() {
    echo "SIGTERM signal received, try to gracefully shutdown all services..."
    gitlab-ctl stop
}

trap "sigterm_handler; exit" TERM


function dbMigrate() {
    # Make sure postgres is up to date 
    gitlab-ctl pg-upgrade -w
    gitlab-ctl start postgresql
    gitlab-rake db:migrate
}

function entrypoint() {
    echo "Entrypoint"

    # Start services
    /opt/gitlab/embedded/bin/runsvdir-start &

    # Fix "No migration with version number "
    unset VERSION
    gitlab-ctl reconfigure
    dbMigrate
    gitlab-ctl tail # tail all logs
    wait
}

entrypoint
wait
